### ISSUE TITLE
"Issueベースの開発" レビュー依頼

### ISSUE THREAD

**Issue by ito-ryo-50a** [ito-ryo-50a/denshi_recipe#6]
### 概要
お世話になっております。

卒業制作の"Issueベースの開発" レビュー依頼です。
お手数ですが、ご確認いただけますでしょうか。

現時点での見積もりではMVPリリースまで
ストーリーポイント：67
見込み時間：134時間
を予定しております。

※ER図と画面遷移図は本Issueの下部に添付しております。

### 実装予定の機能
◽️MVPリリース時
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] アプリケーションのトップ画面
- [ ] レシピ生成機能(食材を指定して生成)
- [ ] レシピ一覧機能
- [ ] レシピ詳細機能
- [ ] レシピのピン留め機能
- [ ] レシピへのコメント機能
- [ ] レシピ共有機能

◽️本リリース時
- [ ] レシピ検索機能
- [ ] レシピ閲覧履歴参照機能
- [ ] 作成済みレシピの評価機能
- [ ] 作成済みレシピからランダムで提案機能
- [ ] レシピ生成機能(料理名を指定して生成)
- [ ] 自作レシピ投稿機能
- [ ] LINEを利用したログイン機能

### 必要なページ
◽️MVPリリース時
- [x] ログイン前TOPページ
- [x] ログイン後TOPページ
- [x] 新規ユーザー登録画面
- [x] ログイン画面
- [ ] プライバシーポリシー表示画面
- [ ] 利用規約表示画面
- [ ] お問い合わせフォーム画面
- [ ] ユーザー情報編集画面
- [ ] パスワード変更メール送信画面
- [ ] メールアドレス変更メール送信画面
- [ ] ニックネーム設定画面
- [ ] 退会操作画面
- [ ] レシピ生成入力画面
- [ ] レシピ詳細画面
- [ ] 公開レシピ一覧画面
- [ ] ピン留めレシピ表示画面

◽️本リリース時
- [ ] ユーザー投稿レシピ作成画面
- [ ] ユーザー投稿レシピ編集画面
- [ ] 作成済みレシピ表示画面
- [ ] レシピ検索画面
- [ ] 検索結果表示画面
- [ ] フォルダ管理画面
- [ ] 閲覧履歴参照画面

[画面遷移図リンクです](https://gyazo.com/38ed5b65f28c54ec48333fa4524b8b2f)

![Image](https://github.com/ito-ryo-50a/portfolio/assets/146784590/2cc4265a-36f6-46c4-a9bb-2d4c6dea8b3d)

[ER図リンクです](https://gyazo.com/34fcd616c26280af3a0a560ac0347c7a)

![Image](https://github.com/ito-ryo-50a/portfolio/assets/146784590/6edd1d90-fc4b-476d-b428-44906c4224da)

**Comment by Tsuchiya2** [comment]
![image](https://github.com/ito-ryo-50a/portfolio/assets/61481161/0299c728-b743-4073-9e80-db78999ea8a0)

projectsにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。
カリキュラムをご確認いただき、上記が確認できる状態でご提出をお願いいたします。

**Comment by ito-ryo-50a** [comment]
お世話になっております。

URLが間違っておりました。
大変申し訳ございません。
修正しましたので、ご確認いただけますでしょうか。

[URL](https://github.com/users/ito-ryo-50a/projects/2?pane=issue&itemId=60251391)

**Comment by kenchasonakai** [comment]
確認できました！
LGTMです！

https://github.com/users/ito-ryo-50a/projects/2/views/1

**Comment by ito-ryo-50a** [comment]
ご確認いただきありがとうございます。
引き続きよろしくお願いいたします。
